from Project_Data.Login_func import *
import re
def test_5_3_1():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    btn_more_option_menu_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_more_option_menu_btn))
    btn_more_option_menu_stores.click()
    time.sleep(1)
    btn_add_store= WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(add_store_btn))
    btn_add_store.click()
    time.sleep(1)
    field_store_name = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_name_field))
    field_store_name.send_keys('שולי')
    time.sleep(1)
    field_store_phone = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_phone_field))
    field_store_phone.send_keys(Keys.CONTROL + 'a')
    field_store_phone.send_keys(Keys.BACKSPACE)
    time.sleep(1)
    country_stores_add_store_field_phone = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_add_store_field_phone_country))
    country_stores_add_store_field_phone.click()
    time.sleep(1)
    IL_stores_add_store_field_phone_country = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_add_store_field_phone_country_IL))
    IL_stores_add_store_field_phone_country.click()
    time.sleep(2)
    field_store_phone.send_keys('1320207423')
    time.sleep(1)
    field_store_city = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_city_field))
    field_store_city.send_keys('רמת גן')
    time.sleep(1)
    field_street_city = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_street_field))
    field_street_city.send_keys('החילזון')
    time.sleep(1)
    field_building_city = WebDriverWait (my_driver, 10).until(EC.presence_of_element_located(store_building_field))
    field_building_city.send_keys('6')
    time.sleep(1)
    btn_stores_add_store = WebDriverWait (my_driver, 10).until(EC.presence_of_element_located(stores_add_store_btn))
    btn_stores_add_store.click()
    time.sleep(1)
    bar_stores_search = WebDriverWait (my_driver, 10).until(EC.presence_of_element_located(store_search_bar))
    bar_stores_search.send_keys('שולי')
    store_count =  WebDriverWait (my_driver, 10).until(EC.presence_of_element_located(count_store))
    store_count_inner=store_count.get_attribute('innerText')
    store_count_num = re.search(r'/d+', store_count_inner)
    store_count_num1 =int(store_count_num.group())
    assert store_count_num1 == 1
    time.sleep(2)
    my_driver.close()
    my_driver.quit()

def test_5_3_3():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    sign_stores_btn1_arrow = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_btn1_arrow_sign))
    sign_stores_btn1_arrow.click()
    time.sleep(1)
    sign_stores_btn2_arrow = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_btn2_arrow_sign))
    sign_stores_btn2_arrow.click()
    time.sleep(2)
    assert sign_stores_btn2_arrow.is_displayed()
    my_driver.close()
    my_driver.quit()

def test_5_3_4():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row))
    row_stores_specialty_store.click()
    time.sleep(1)
    name_stores_specialty_store_field = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_field_name))
    name_stores_specialty_store_field.send_keys(Keys.CONTROL + 'a')
    time.sleep(1)
    name_stores_specialty_store_field.send_keys('כוכבה')
    time.sleep(1)
    btn_stores_update_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_update_store_btn))
    btn_stores_update_store.click()
    time.sleep(1)
    tab_store_name = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_name_tab))
    tab_store_name_inner = tab_store_name.get_attribute('innerText')
    assert tab_store_name_inner == 'כוכבה'
    time.sleep(2)
    my_driver.close()
    my_driver.quit()

def test_5_3_5():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row))
    row_stores_specialty_store.click()
    time.sleep(1)
    phone_stores_specialty_store_field = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_field_phone))
    phone_stores_specialty_store_field.send_keys(Keys.CONTROL + 'a')
    phone_stores_specialty_store_field.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    country_stores_specialty_store_field_phone = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_field_phone_country))
    country_stores_specialty_store_field_phone.click()
    time.sleep(1)
    IL_stores_specialty_store_field_phone_country = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_field_phone_country_IL))
    IL_stores_specialty_store_field_phone_country.click()
    time.sleep(2)
    phone_stores_specialty_store_field.send_keys('1320207123')
    time.sleep(2)
    btn_stores_update_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_update_store_btn))
    btn_stores_update_store.click()
    time.sleep(1)
    tab_store_phone = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_phone_tab))
    tab_store_phone_inner = tab_store_phone.get_attribute('innerText')
    assert tab_store_phone_inner == '9721320207123'
    time.sleep(2)
    my_driver.close()
    my_driver.quit()



def test_5_3_6():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row))
    row_stores_specialty_store.click()
    time.sleep(1)
    city_stores_specialty_store_field= WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_field_city))
    city_stores_specialty_store_field.send_keys(Keys.CONTROL + 'a')
    city_stores_specialty_store_field.send_keys('חולון')
    time.sleep(1)
    btn_stores_update_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_update_store_btn))
    btn_stores_update_store.click()
    time.sleep(1)
    bar_stores_search = WebDriverWait (my_driver, 10).until(EC.presence_of_element_located(store_search_bar))
    bar_stores_search.send_keys('כוכבה')
    time.sleep(1)
    search_row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row_search))
    search_row_stores_specialty_store.click()
    time.sleep(1)
    search_row_stores_specialty_store_city_field = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_city_field))
    search_row_stores_specialty_store_city_field_default_Value = search_row_stores_specialty_store_city_field.get_attribute('defaultValue')
    time.sleep(1)
    assert search_row_stores_specialty_store_city_field_default_Value == "חולון"
    time.sleep(2)
    my_driver.close()
    my_driver.quit()

def test_5_3_7():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row))
    row_stores_specialty_store.click()
    time.sleep(1)
    street_stores_specialty_store_field= WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_field_street))
    street_stores_specialty_store_field.send_keys(Keys.CONTROL + 'a')
    street_stores_specialty_store_field.send_keys('השבלול')
    time.sleep(1)
    btn_stores_update_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_update_store_btn))
    btn_stores_update_store.click()
    time.sleep(1)
    bar_stores_search = WebDriverWait (my_driver, 10).until(EC.presence_of_element_located(store_search_bar))
    bar_stores_search.send_keys('כוכבה')
    time.sleep(1)
    search_row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row_search))
    search_row_stores_specialty_store.click()
    time.sleep(1)
    search_row_stores_specialty_store_street_field = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_street_field))
    search_row_stores_specialty_store_street_field_default_Value = search_row_stores_specialty_store_street_field.get_attribute('defaultValue')
    time.sleep(1)
    assert search_row_stores_specialty_store_street_field_default_Value == "השבלול"
    time.sleep(2)
    my_driver.close()
    my_driver.quit()

def test_5_3_8():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row))
    row_stores_specialty_store.click()
    time.sleep(1)
    building_stores_specialty_store_field = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_field_building))
    building_stores_specialty_store_field.send_keys(Keys.CONTROL + 'a')
    building_stores_specialty_store_field.send_keys('3')
    time.sleep(1)
    btn_stores_update_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_update_store_btn))
    btn_stores_update_store.click()
    time.sleep(1)
    bar_stores_search = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_search_bar))
    bar_stores_search.send_keys('כוכבה')
    time.sleep(1)
    search_row_stores_specialty_store = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_specialty_store_row_search))
    search_row_stores_specialty_store.click()
    time.sleep(1)
    search_row_stores_specialty_store_building_field = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_building_field))
    search_row_stores_specialty_store_building_field_default_Value = search_row_stores_specialty_store_building_field.get_attribute('defaultValue')
    time.sleep(1)
    assert search_row_stores_specialty_store_building_field_default_Value == "3"
    time.sleep(2)
    my_driver.close()
    my_driver.quit()

def test_5_3_9():
    my_driver = login_web()
    tab_stores = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(stores_tab))
    tab_stores.click()
    time.sleep(1)
    bar_stores_search = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_search_bar))
    bar_stores_search.send_keys('שופרסלטסטטטטטטט')
    time.sleep(1)
    tab_store_search_name = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located(store_search_name_tab))
    tab_store_name_inner = tab_store_search_name.get_attribute('innerText')
    assert tab_store_name_inner == 'שופרסלטסטטטטטטט'
    time.sleep(2)
    my_driver.close()
    my_driver.quit()